export enum Exception {
    DEFAULT = 0,
    INVALID_INPUT = 100,
    UNAUTHORIZED = 101,
    DUPLICATE_EMAIL = 102,
    DUPLICATE_USERNAME = 103,
    INVALID_CREDENTIALS = 104,
    UNCONFIRMED_ACCOUNT = 105,
    EMAIL_NOT_FOUND = 106,
    INVALID_ACCOUNT_TYPE = 107,
    ALREADY_CONFIRMED_ACCOUNT = 108
}