import { Time } from './time';

export const Redis = {
    GOOGLE_API_PREFIX: 'google_api',
    GOOGLE_API_NOT_AVAILABLE: 'NOT_AVAILABLE',
    GOOGLE_API_EXPIRATION_TIME: Time.MINUTES_5,
    EVENT: {
        SEND: 'REDIS_SOCKET_EVENT_SEND',
        EMIT_ALL: 'REDIS_SOCKET_EVENT_EMIT_ALL',
        EMIT_AUTHENTICATED: 'REDIS_SOCKET_EVENT_EMIT_AUTHENTICATED'
    }
} as const;
